import { Severity, Weather, Temperature } from "@prisma/client";

export const logs = [
  {
    title: "Runny nose and headache all day",
    severity: Severity.THREE,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.SUNNY,
    temperature: Temperature.WARM,
    eatenToday: ["Peanut Butter Toast", "Orange Juice"],
    drankToday: ["Black Coffee"],
    toiletriesUsed: ["Shampoo", "Face Wash"],
  },
  {
    title: "Slight fever with sore throat",
    severity: Severity.TWO,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.CLOUDY,
    temperature: Temperature.HOT,
    eatenToday: ["Scrambled Eggs", "Toast"],
    drankToday: ["Tea"],
    toiletriesUsed: ["Toothpaste", "Shower Gel"],
  },
  {
    title: "Stomach ache after eating spicy food",
    severity: Severity.TWO,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.RAINY,
    temperature: Temperature.COLD,
    eatenToday: ["Chili Con Carne", "Rice"],
    drankToday: ["Water"],
    toiletriesUsed: ["Body Wash", "Shaving Cream"],
  },
  {
    title: "Fatigue and muscle pain from workout",
    severity: Severity.ONE,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.SUNNY,
    temperature: Temperature.WARM,
    eatenToday: ["Protein Shake", "Banana"],
    drankToday: ["Coconut Water"],
    toiletriesUsed: ["Shower Gel", "Deodorant"],
  },
  {
    title: "Allergic reaction to pollen",
    severity: Severity.THREE,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.SUNNY,
    temperature: Temperature.HOT,
    eatenToday: ["Salad", "Apple"],
    drankToday: ["Green Tea"],
    toiletriesUsed: ["Face Wash", "Sunscreen"],
  },
  {
    title: "Cold symptoms with congestion",
    severity: Severity.ONE,
    userId: Math.floor(Math.random() * 10),
    weather: Weather.CLOUDY,
    temperature: Temperature.COLD,
    eatenToday: ["Chicken Soup", "Crackers"],
    drankToday: ["Herbal Tea"],
    toiletriesUsed: ["Hand Sanitizer", "Tissues"],
  },
];
